# What provide Numpy to Python ?

- `ndarray` multi-dimensional array object
- derived objects such as masked arrays and matrices
- `ufunc` fast array mathematical operations.
- Offers some Matlab-ish capabilities within Python
- Initially developed by [Travis Oliphant](https://www.continuum.io/people/travis-oliphant).
- Numpy 1.0 released October, 2006.
- The [SciPy.org website](https://docs.scipy.org/doc/numpy) is very helpful.
- NumPy fully supports an object-oriented approach.

# Routines for fast operations on arrays.

    - shape manipulation
    - sorting
    - I/O
    - FFT
    - basic linear algebra
    - basic statistical operations
    - random simulation
    - statistics
    - and much more...

# Getting Started with NumPy

- It is handy to import everything from NumPy into a Python console:
```python
from numpy import *
```
- But it is easier to read and debug if you use explicit imports.
```python
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
```

In [1]:
import numpy as np
print(np.__version__)

ModuleNotFoundError: No module named 'numpy'

# Why Arrays ?

- Python lists are slow to process and use a lot of memory.
- For tables, matrices, or volumetric data, you need lists of lists of lists... which becomes messy to program.

In [2]:
from random import random
from operator import truediv

In [3]:
l1 = [random() for i in range(1000)]
l2 = [random() for i in range(1000)]
%timeit s = sum(map(truediv,l1,l2))

42.8 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
a1 = np.array(l1)
a2 = np.array(l2)
%timeit s = np.sum(a1/a2)

NameError: name 'np' is not defined

# Numpy Arrays: The `ndarray` class.

- There are important differences between NumPy arrays and Python lists:
    - NumPy arrays have a fixed size at creation.
    - NumPy arrays elements are all required to be of the same data type.
    - NumPy arrays operations are performed in compiled code for performance.
- Most of today's scientific/mathematical Python-based software use NumPy arrays.
- NumPy gives us the code simplicity of Python, but the operation is speedily executed by pre-compiled C code.

In [5]:
a = np.array([0,1,2,3])  #  list
b = np.array((4,5,6,7))  #  tuple
c = np.matrix('8 9 0 1') #  string (matlab syntax)

NameError: name 'np' is not defined

In [6]:
print(a,b,c)

NameError: name 'a' is not defined

## Element wise operations are the “default mode” 

In [7]:
a*b,a+b

NameError: name 'a' is not defined

In [8]:
5*a, 5+a

NameError: name 'a' is not defined

In [9]:
a @ b, np.dot(a,b)  # Matrix multiplication

NameError: name 'a' is not defined

#  NumPy Arrays Properties

In [10]:
a = np.array([1,2,3,4,5]) # Simple array creation

NameError: name 'np' is not defined

In [11]:
type(a) # Checking the type

NameError: name 'a' is not defined

In [12]:
a.dtype # Print numeric type of elements

NameError: name 'a' is not defined

In [13]:
a.itemsize # Print Bytes per element

NameError: name 'a' is not defined

In [14]:
a.shape # returns a tuple listing the length along each dimension

NameError: name 'a' is not defined

In [15]:
np.size(a), a.size # returns the entire number of elements.

NameError: name 'np' is not defined

In [16]:
a.ndim  # Number of dimensions

NameError: name 'a' is not defined

In [17]:
a.nbytes # Memory used

NameError: name 'a' is not defined

- ** Always use `shape` or `size` for numpy arrays instead of `len` **
- `len` gives same information only for 1d array.

# Functions to allocate arrays

In [18]:
x = np.zeros((2,),dtype=('i4,f4,a10'))
x

NameError: name 'np' is not defined

`empty, empty_like, ones, ones_like, zeros, zeros_like, full, full_like`

#  Setting Array Elements Values

In [19]:
a = np.array([1,2,3,4,5])
print(a.dtype)

NameError: name 'np' is not defined

In [20]:
a[0] = 10 # Change first item value
a, a.dtype

NameError: name 'a' is not defined

In [21]:
a.fill(0) # slighty faster than a[:] = 0
a

NameError: name 'a' is not defined

# Setting Array Elements Types

In [22]:
b = np.array([1,2,3,4,5.0]) # Last item is a float
b, b.dtype

NameError: name 'np' is not defined

In [23]:
a.fill(3.0)  # assigning a float into a int array 
a[1] = 1.5   # truncates the decimal part
print(a.dtype, a)

NameError: name 'a' is not defined

In [24]:
a.astype('float64') # returns a new array containing doubles

NameError: name 'a' is not defined

In [25]:
np.asfarray([1,2,3,4]) # Return an array converted to a float type

NameError: name 'np' is not defined

# Slicing x[lower:upper:step]
- Extracts a portion of a sequence by specifying a lower and upper bound.
- The lower-bound element is included, but the upper-bound element is **not** included.
- The default step value is 1 and can be negative.

In [26]:
a = np.array([10,11,12,13,14])

NameError: name 'np' is not defined

In [27]:
a[:2], a[-5:-3], a[0:2], a[-2:] # negative indices work

NameError: name 'a' is not defined

In [28]:
a[::2], a[::-1]

NameError: name 'a' is not defined

### Exercise: 
- Compute derivative of $f(x) = \sin(x)$ with finite difference method.
$$
    \frac{\partial f}{\partial x} \sim \frac{f(x+dx)-f(x)}{dx}
$$

derivatives values are centered in-between sample points.

In [29]:
x, dx = np.linspace(0,4*np.pi,100, retstep=True)
y = np.sin(x)

NameError: name 'np' is not defined

In [30]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [12.,8.] # Increase plot size
plt.plot(x, np.cos(x),'b')
plt.title(r"$\rm{Derivative\ of}\ \sin(x)$");

ModuleNotFoundError: No module named 'matplotlib'

In [31]:
# Compute integral of x numerically
avg_height = 0.5*(y[1:]+y[:-1])
int_sin = np.cumsum(dx*avg_height)
plt.plot(x[1:], int_sin, 'ro', x, np.cos(0)-np.cos(x));

NameError: name 'y' is not defined

# Multidimensional array

In [32]:
a = np.arange(4*3).reshape(4,3) # NumPy array
l = [[0,1,2],[3,4,5],[6,7,8],[9,10,11]] # Python List

NameError: name 'np' is not defined

In [33]:
print(a)
print(l)

NameError: name 'a' is not defined

In [34]:
l[-1][-1] # Access to last item

NameError: name 'l' is not defined

In [35]:
print(a[-1,-1])  # Indexing syntax is different with NumPy array
print(a[0,0])    # returns the first item
print(a[1,:])    # returns the second line

NameError: name 'a' is not defined

In [36]:
print(a[1]) # second line with 2d array
print(a[:,-1])  # last column

NameError: name 'a' is not defined

### Exercise 
- We compute numerically the Laplace Equation Solution using Finite Difference Method
- Replace the computation of the discrete form of Laplace equation with numpy arrays
$$
T_{i,j} = \frac{1}{4} ( T_{i+1,j} + T_{i-1,j} + T_{i,j+1} + T_{i,j-1})
$$
- The function numpy.allclose can help you to compute the residual.

In [37]:
%%time
# Boundary conditions
Tnorth, Tsouth, Twest, Teast = 100, 20, 50, 50

# Set meshgrid
n, l = 64, 1.0
X, Y = np.meshgrid(np.linspace(0,l,n), np.linspace(0,l,n))
T = np.zeros((n,n))

# Set Boundary condition
T[n-1:, :] = Tnorth
T[:1, :]   = Tsouth
T[:, n-1:] = Teast
T[:, :1]   = Twest

residual = 1.0   
istep = 0
while residual > 1e-5 :
    istep += 1
    print ((istep, residual), end="\r")
    residual = 0.0   
    for i in range(1, n-1):
        for j in range(1, n-1):
            T_old = T[i,j]
            T[i, j] = 0.25 * (T[i+1,j] + T[i-1,j] + T[i,j+1] + T[i,j-1])
            if T[i,j]>0:
                residual=max(residual,abs((T_old-T[i,j])/T[i,j]))


print()
print("iterations = ",istep)
plt.title("Temperature")
plt.contourf(X, Y, T)
plt.colorbar()

NameError: name 'np' is not defined

# Arrays to ASCII files


In [38]:
x = y = z = np.arange(0.0,5.0,1.0)

NameError: name 'np' is not defined

In [39]:
np.savetxt('test.out', (x,y,z), delimiter=',')   # X is an array
%cat test.out

NameError: name 'np' is not defined

In [40]:
np.savetxt('test.out', (x,y,z), fmt='%1.4e')   # use exponential notation
%cat test.out

NameError: name 'np' is not defined

# Arrays from ASCII files

In [41]:
np.loadtxt('test.out')

NameError: name 'np' is not defined

- [save](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.save.html#numpy.save): Save an array to a binary file in NumPy .npy format
- [savez](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez.html#numpy.savez) : Save several arrays into an uncompressed .npz archive
- [savez_compressed](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez_compressed.html#numpy.savez_compressed): Save several arrays into a compressed .npz archive
- [load](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.load.html#numpy.load): Load arrays or pickled objects from .npy, .npz or pickled files.

## H5py

Pythonic interface to the HDF5 binary data format. [h5py user manual](http://docs.h5py.org)

In [42]:
import h5py as h5

with h5.File('test.h5','w') as f:
    f['x'] = x
    f['y'] = y
    f['z'] = z

ModuleNotFoundError: No module named 'h5py'

In [43]:
with h5.File('test.h5','r') as f:
    for field in f.keys():
        print(field+':',f[field].value)

NameError: name 'h5' is not defined

# Slices Are References
- Slices are references to memory in the original array.
- Changing values in a slice also changes the original array.


In [44]:
a = np.arange(10)
b = a[3:6]
b  # `b` is a view of array `a` and `a` is called base of `b`

NameError: name 'np' is not defined

In [45]:
b[0] = -1
a  # you change a view the base is changed.

NameError: name 'b' is not defined

- Numpy does not copy if it is not necessary to save memory.

In [46]:
c = a[7:8].copy() # Explicit copy of the array slice
c[0] = -1 
a

NameError: name 'a' is not defined

# Fancy Indexing

In [47]:
a = np.fromfunction(lambda i, j: (i+1)*10+j, (4, 5), dtype=int)
a

NameError: name 'np' is not defined

In [48]:
np.random.shuffle(a.flat) # shuffle modify only the first axis
a

NameError: name 'np' is not defined

In [49]:
locations = a % 3 == 0 # locations can be used as a mask
a[locations] = 0 #set to 0 only the values that are divisible by 3
a

NameError: name 'a' is not defined

In [50]:
a += a == 0
a

NameError: name 'a' is not defined

### `numpy.take`

In [51]:
a[1:3,2:5]

NameError: name 'a' is not defined

In [52]:
np.take(a,[[6,7],[10,11]])  # Use flatten array indices

NameError: name 'np' is not defined

# Changing array shape

In [53]:
grid = np.indices((2,3)) # Return an array representing the indices of a grid.
grid[0]

NameError: name 'np' is not defined

In [54]:
grid[1]

NameError: name 'grid' is not defined

In [55]:
grid.flat[:] # Return a view of grid array

NameError: name 'grid' is not defined

In [56]:
grid.flatten() # Return a copy

NameError: name 'grid' is not defined

In [57]:
np.ravel(grid, order='C') # A copy is made only if needed.

NameError: name 'np' is not defined

# Sorting

In [58]:
a=np.array([5,3,6,1,6,7,9,0,8])
np.sort(a) #. Return a view

NameError: name 'np' is not defined

In [59]:
a

NameError: name 'a' is not defined

In [60]:
a.sort() # Change the array inplace
a

NameError: name 'a' is not defined

# Transpose-like operations

In [61]:
a = np.array([5,3,6,1,6,7,9,0,8])
b = a
b.shape = (3,3) # b is a reference so a will be changed

NameError: name 'np' is not defined

In [62]:
a

NameError: name 'a' is not defined

In [63]:
c = a.T # Return a view so a is not changed
np.may_share_memory(a,c)

NameError: name 'a' is not defined

In [64]:
c[0,0] = -1 # c is stored in same memory so change c you change a
a

NameError: name 'c' is not defined

In [65]:
c  # is a transposed view of a

NameError: name 'c' is not defined

In [66]:
b  # b is a reference to a

NameError: name 'b' is not defined

In [67]:
c.base  # When the array is not a view `base` return None

NameError: name 'c' is not defined

# Methods Attached to NumPy Arrays

In [68]:
a = np.arange(20).reshape(4,5)
np.random.shuffle(a.flat)
a

NameError: name 'np' is not defined

In [69]:
a = (a - a.mean())/ a.std() # Standardize the matrix
print(a)

NameError: name 'a' is not defined

In [70]:
np.set_printoptions(precision=4)
print(a)

NameError: name 'np' is not defined

In [71]:
a.argmax() # max position in the memory contiguous array

NameError: name 'a' is not defined

In [72]:
np.unravel_index(a.argmax(),a.shape) # get position in the matrix

NameError: name 'np' is not defined

# Array Operations over a given axis

In [73]:
a = np.arange(20).reshape(5,4)
np.random.shuffle(a.flat)

NameError: name 'np' is not defined

In [74]:
a.sum(axis=0) # sum of each column

NameError: name 'a' is not defined

In [75]:
np.apply_along_axis(sum, axis=0, arr=a)

NameError: name 'np' is not defined

In [76]:
np.apply_along_axis(sorted, axis=0, arr=a)

NameError: name 'np' is not defined

You can replace the `sorted` builtin fonction by a user defined function.

In [77]:
np.empty(10)

NameError: name 'np' is not defined

In [78]:
np.linspace(0,2*np.pi,10)

NameError: name 'np' is not defined

In [79]:
np.arange(0,2.+0.4,0.4)

NameError: name 'np' is not defined

In [80]:
np.eye(4)

NameError: name 'np' is not defined

In [81]:
a = np.diag(range(4))
a

NameError: name 'np' is not defined

In [82]:
a[:,:,np.newaxis]

NameError: name 'a' is not defined

### Create the following arrays
```python
[100 101 102 103 104 105 106 107 108 109]
```
Hint: numpy.arange
```python
[-2. -1.8 -1.6 -1.4 -1.2 -1. -0.8 -0.6 -0.4 -0.2 0. 
0.2 0.4 0.6 0.8 1. 1.2 1.4 1.6 1.8]
```
Hint: numpy.linspace
```python
[[ 0.001	0.00129155 0.0016681 0.00215443 0.00278256 
     0.003593810.00464159 0.00599484 0.00774264 0.01]
```
Hint: numpy.logspace
```python
[[ 0. 0. -1. -1. -1.] 
 [ 0. 0.  0. -1. -1.] 
 [ 0. 0.  0.  0. -1.]
 [ 0. 0.  0.  0.  0.]
 [ 0. 0.  0.  0.  0.] 
 [ 0. 0.  0.  0.  0.] 
 [ 0. 0.  0.  0.  0.]]
```
Hint: numpy.tri, numpy.zeros, numpy.transpose

```python
[[ 0.  1.  2.  3. 4.] 
 [-1.  0.  1.  2. 3.] 
 [-1. -1.  0.  1. 2.] 
 [-1. -1. -1.  0. 1.] 
 [-1. -1. -1. -1. 0.]]
```
Hint: numpy.ones, numpy.diag

* Compute the integral numerically with Trapezoidal rule
$$
I = \int_{-\infty}^\infty e^{-v^2} dv
$$
with  $v \in [-10;10]$ and n=20.



# Views and Memory Management
- If it exists one view of a NumPy array, it can be destroyed.


In [83]:
big = np.arange(1000000)
small = big[:5]
del big
small.base

NameError: name 'np' is not defined

- Array called `big` is still allocated.
- Sometimes it is better to create a copy.

In [84]:
big = np.arange(1000000)
small = big[:5].copy()
del big
print(small.base)

NameError: name 'np' is not defined

## Change memory alignement

In [85]:
del(a)
a = np.arange(20).reshape(5,4)
print(a.flags)

NameError: name 'a' is not defined

In [86]:
b = np.asfortranarray(a) # makes a copy
b.flags

NameError: name 'np' is not defined

In [87]:
b.base is a

NameError: name 'b' is not defined

You can also create a fortran array with array function.

In [88]:
c = np.array([[1,2,3],[4,5,6]])
f = np.asfortranarray(c)

NameError: name 'np' is not defined

In [89]:
print(f.ravel(order='K')) # Return a 1D array using memory order
print(c.ravel(order='K')) # Copy is made only if necessary

NameError: name 'f' is not defined

# Broadcasting rules

Broadcasting rules allow you to make an outer product between two vectors: the first method involves array tiling, the second one involves broadcasting. The last method is significantly faster.


In [90]:
n = 1000
a = np.arange(n)
ac = a[:, np.newaxis]   # column matrix
ar = a[np.newaxis, :]   # row matrix

NameError: name 'np' is not defined

In [91]:
%timeit np.tile(a, (n,1)).T * np.tile(a, (n,1))

NameError: name 'np' is not defined

In [92]:
%timeit ac * ar

NameError: name 'ac' is not defined

In [93]:
np.all(np.tile(a, (n,1)).T * np.tile(a, (n,1)) == ac * ar)

NameError: name 'np' is not defined

# Numpy Matrix

Specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as $*$ (matrix multiplication) and $**$ (matrix power).

In [94]:
m = np.matrix('1 2; 3 4') #Matlab syntax
m

NameError: name 'np' is not defined

In [95]:
a = np.matrix([[1, 2],[ 3, 4]]) #Python syntax
a

NameError: name 'np' is not defined

In [96]:
a = np.arange(1,4)
b = np.mat(a) # 2D view, no copy!
b, np.may_share_memory(a,b)

NameError: name 'np' is not defined

In [97]:
a = np.matrix([[1, 2, 3],[ 3, 4, 5]])
a * b.T # Matrix vector product

NameError: name 'np' is not defined

In [98]:
m * a # Matrix multiplication

NameError: name 'm' is not defined

## StructuredArray using a compound data type specification

In [99]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

NameError: name 'np' is not defined

In [100]:
data['name'] = ['Pierre', 'Paul', 'Jacques', 'Francois']
data['age'] = [45, 10, 71, 39]
data['weight'] = [95.0, 75.0, 88.0, 71.0]
print(data)

NameError: name 'data' is not defined

## RecordArray

In [101]:
data_rec = data.view(np.recarray)
data_rec.age

NameError: name 'data' is not defined

# NumPy Array Programming
- Array operations are fast, Python loops are slow. 
- Top priority: **avoid loops**
- It’s better to do the work three times witharray operations than once with a loop.
- This does require a change of habits.
- This does require some experience.
- NumPy’s array operations are designed to make this possible.

# Fast Evaluation Of Array Expressions 

- The `numexpr` package supplies routines for the fast evaluation of array expressions elementwise by using a vector-based virtual machine.
- Expressions are cached, so reuse is fast.

[Numexpr Users Guide](https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide)

In [102]:
import numexpr as ne
import numpy as np
nrange = (2 ** np.arange(6, 24)).astype(int)

t_numpy = []
t_numexpr = []

for n in nrange:
    a = np.random.random(n)
    b = np.arange(n, dtype=np.double)
    c = np.random.random(n)
    
    c1 = ne.evaluate("a ** 2 + b ** 2 + 2 * a * b * c ", optimization='aggressive')

    t1 = %timeit -oq -n 10 a ** 2 + b ** 2 + 2 * a * b * c
    t2 = %timeit -oq -n 10 ne.re_evaluate()

    t_numpy.append(t1.best)
    t_numexpr.append(t2.best)

%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
import seaborn; seaborn.set()

plt.loglog(nrange, t_numpy, label='numpy')
plt.loglog(nrange, t_numexpr, label='numexpr')

plt.legend(loc='lower right')
plt.xlabel('Vectors size')
plt.ylabel('Execution Time (s)');

ModuleNotFoundError: No module named 'numexpr'

# References
- [NumPy reference](http://docs.scipy.org/doc/numpy/reference/)
- [Getting the Best Performance out of NumPy](http://ipython-books.github.io/featured-01/)
- [Numpy by Konrad Hinsen](http://calcul.math.cnrs.fr/Documents/Ecoles/2013/python/NumPy%20avance.pdf)